import type { Flow } from './flow';

/** Emits a standalone, typed TypeScript module for a compiled flow. */
export function emitFlowModule(flow: Flow): string {
  const paramType =
    flow.parameters.length === 0
      ? 'Record<string, never>'
      : `{\n${flow.parameters.map((p) => `  /** e.g. ${JSON.stringify(p.example)} */\n  ${p.name}: string;`).join('\n')}\n}`;

  return `// Generated by @bellwether/compile from trial ${flow.sourceTrialId} (run ${flow.sourceRunId}).
// Do not edit by hand: re-compile from a fresh trace when the application changes.
import { FlowCursor } from '@bellwether/compile';
import type { Flow } from '@bellwether/compile';

export type ${pascal(flow.taskId)}Params = ${paramType};

export const flow: Flow = ${JSON.stringify(flow, null, 2)};

export function cursor(params: ${pascal(flow.taskId)}Params): FlowCursor {
  return new FlowCursor(flow, { params });
}
`;
}

/**
 * Emits an MCP server exposing each flow as a tool.
 *
 * This is the payoff of the whole exercise: a GUI-only internal system that had no
 * integration surface now has typed, callable tools with assertions, and anything
 * that speaks MCP can drive it without a model in the loop.
 */
export function emitMcpServer(flows: Flow[]): string {
  const tools = flows.map((flow) => ({
    name: `run_${flow.taskId.replace(/[^a-zA-Z0-9_]/g, '_')}`,
    description: `Compiled flow for ${flow.taskId} (${flow.steps.length} steps, recorded from trial ${flow.sourceTrialId}).`,
    inputSchema: {
      type: 'object',
      properties: Object.fromEntries(
        flow.parameters.map((parameter) => [
          parameter.name,
          { type: 'string', description: `e.g. ${parameter.example}` },
        ]),
      ),
      required: flow.parameters.map((parameter) => parameter.name),
    },
  }));

  return `#!/usr/bin/env node
// Generated by @bellwether/compile. Exposes compiled flows as MCP tools over stdio.
//
// Each tool drives a real surface, so the caller supplies the surface: this server
// is deliberately not wired to a driver by default. Fill in openSurface() with a
// @bellwether/solari driver for your environment.
import { FlowCursor } from '@bellwether/compile';

const FLOWS = ${JSON.stringify(Object.fromEntries(flows.map((flow) => [flow.taskId, flow])), null, 2)};

const TOOLS = ${JSON.stringify(tools, null, 2)};

async function openSurface(_taskId) {
  throw new Error('openSurface() is not implemented: wire it to a @bellwether/solari driver');
}

async function callTool(name, args) {
  const taskId = Object.keys(FLOWS).find((id) => name === 'run_' + id.replace(/[^a-zA-Z0-9_]/g, '_'));
  if (!taskId) throw new Error('unknown tool ' + name);
  const surface = await openSurface(taskId);
  const cursor = new FlowCursor(FLOWS[taskId], { params: args });
  for (;;) {
    const frame = await surface.observe();
    const action = cursor.next(frame.screenText);
    if (action.kind === 'done') return { ok: true, steps: cursor.result.stepsExecuted };
    if (action.kind === 'abstain') return { ok: false, error: action.reason };
    await surface.apply(action);
  }
}

process.stdin.setEncoding('utf8');
let buffer = '';
process.stdin.on('data', async (chunk) => {
  buffer += chunk;
  let index;
  while ((index = buffer.indexOf('\\n')) >= 0) {
    const line = buffer.slice(0, index).trim();
    buffer = buffer.slice(index + 1);
    if (!line) continue;
    const request = JSON.parse(line);
    const send = (result) =>
      process.stdout.write(JSON.stringify({ jsonrpc: '2.0', id: request.id, result }) + '\\n');
    try {
      if (request.method === 'initialize') {
        send({ protocolVersion: '2024-11-05', serverInfo: { name: 'bellwether-flows', version: '0.1.0' }, capabilities: { tools: {} } });
      } else if (request.method === 'tools/list') {
        send({ tools: TOOLS });
      } else if (request.method === 'tools/call') {
        const output = await callTool(request.params.name, request.params.arguments ?? {});
        send({ content: [{ type: 'text', text: JSON.stringify(output) }] });
      } else {
        send({});
      }
    } catch (error) {
      process.stdout.write(
        JSON.stringify({ jsonrpc: '2.0', id: request.id, error: { code: -32603, message: String(error) } }) + '\\n',
      );
    }
  }
});
`;
}

function pascal(text: string): string {
  return text
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}
